DROP INDEX IF EXISTS pursuit_outcomes_analysis_id_idx;
DROP INDEX IF EXISTS pursuit_decisions_analysis_id_idx;
DROP INDEX IF EXISTS email_verification_tokens_token_hash_idx;
DROP INDEX IF EXISTS email_verification_tokens_user_id_idx;
DROP INDEX IF EXISTS client_memory_workspace_client_uidx;
DROP INDEX IF EXISTS client_memory_client_key_idx;
DROP INDEX IF EXISTS client_memory_workspace_id_idx;
DROP INDEX IF EXISTS credential_suggestions_workspace_id_idx;
DROP INDEX IF EXISTS workspace_credentials_workspace_id_idx;
DROP INDEX IF EXISTS rfp_analyses_workspace_id_idx;
DROP INDEX IF EXISTS agency_profiles_workspace_uidx;
DROP INDEX IF EXISTS agency_profiles_workspace_id_idx;
DROP INDEX IF EXISTS workspace_memberships_workspace_user_uidx;
DROP INDEX IF EXISTS workspace_memberships_workspace_id_idx;
DROP INDEX IF EXISTS workspace_memberships_user_id_idx;

DROP TABLE IF EXISTS pursuit_outcomes;
DROP TABLE IF EXISTS pursuit_decisions;
DROP TABLE IF EXISTS email_verification_tokens;
DROP TABLE IF EXISTS workspace_preferences_history;
DROP TABLE IF EXISTS client_memory;
DROP TABLE IF EXISTS credential_suggestions;
DROP TABLE IF EXISTS workspace_credentials;
ALTER TABLE rfp_analyses DROP COLUMN IF EXISTS workspace_id;
DROP TABLE IF EXISTS agency_profiles;
DROP TABLE IF EXISTS workspace_domains;
DROP TABLE IF EXISTS workspace_memberships;
DROP TABLE IF EXISTS workspaces;
ALTER TABLE users DROP COLUMN IF EXISTS email_verified_at;
